[package]
name = "dojo_examples"
version = "0.1.0"

[dependencies]
core = { git = "https://github.com/starkware-libs/cairo.git", version = "v1.0.0-alpha.5", rev = "f3d940ace1a336f8714fcbf855874061a29ad009" }
dojo = { path = "../lib" }

[[target.dojo]]

[tool.dojo]
world_address = "0xdead"
initializer_class_hash = "0xbeef"

[tool.dojo.testnet]
rpc = "https://rpc.testnet.starkware.co"
