name: release-dispatch
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release
        required: true
        type: string

jobs:
  release:
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dojoengine/dojo-dev:f6a4b8a
    steps:
      # Workaround described here: https://github.com/actions/checkout/issues/760
      - run: git config --global --add safe.directory /__w/dojo/dojo/
      - uses: actions/checkout@v3
      - run: cargo release ${{ inputs.version }} --no-publish --no-verify --execute
      - uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Prepare release: ${{ inputs.version }}"
          commit-message: "Prepare release: ${{ inputs.version }}"
          branch: prepare-release
          base: main
          delete-branch: true
